name: Build

on:
  push:
    paths:
      - patches/**.patch
      - scripts/**.sh
      - pom.xml
      - settings.xml
  pull_request:
    paths:
      - patches/**.patch
      - scripts/**.sh
  workflow_dispatch:

jobs:
  build:
    name: Build (Java ${{ matrix.java }})
    strategy:
      matrix:
        java:
          - "21"
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v5
      - id: setup-java
        name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          cache: maven
      - id: setup-git
        name: Setup Git
        run: |
          git config --global user.email "ci@github.com"
          git config --global user.name "GitHub CI"
      - id: setup-maven
        name: Setup Maven
        shell: bash
        run: mkdir .mvn && cp .github/maven.config .mvn
      - id: build
        name: Build SportPaper
        run: bash sportpaper jar
      - id: upload
        name: Upload SportPaper
        uses: actions/upload-artifact@v4
        with:
          name: SportPaper.jar
          path: sportpaper.jar
          if-no-files-found: error
      - id: deploy
        if: |
          github.repository_owner == 'Electroid' &&
          github.ref == 'refs/heads/main'
        name: Deploy SportPaper
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
